name = "OPT-ServerMod"
modname = "opt-server"
prefix = "opt_server"
author = "Operation Pandora Trigger"

files = [
    "mod.cpp",
    "LICENSE",
    "README.md"
]

releasebuild = [
    "@zip opt-servermod_v{{semver.major}}.{{semver.minor}}.{{semver.patch}}.{{semver.build}}"
]

key_name = "opt_server_v{{semver.major}}.{{semver.minor}}.{{semver.patch}}.{{semver.build}}"
authority = "opt_server_v{{semver.major}}.{{semver.minor}}.{{semver.patch}}.{{semver.build}}"
